# Generated by Django 6.0.7 on 2026-07-26 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0002_roleedge_rolepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope_type", models.CharField(blank=True, max_length=64, null=True)),
                ("scope_id", models.CharField(blank=True, max_length=64, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "principal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="rbac.role",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("scope_id__isnull", False)),
                        fields=("principal", "role", "scope_type", "scope_id"),
                        name="rbac_assignment_unique_scoped",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("scope_id__isnull", True)),
                        fields=("principal", "role"),
                        name="rbac_assignment_unique_global",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("scope_id__isnull", True), ("scope_type__isnull", True)
                            ),
                            models.Q(
                                ("scope_id__isnull", False),
                                ("scope_type__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="rbac_assignment_scope_both_or_neither",
                    ),
                ],
            },
        ),
    ]
